-- liquibase formatted SQL

--changeset kuat:1
CREATE TABLE IF NOT EXISTS BRANDS
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP    NULL
);

--changeset kuat:2
CREATE TABLE IF NOT EXISTS CATEGORIES
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION TEXT,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP    NULL
);

--changeset kuat:3
CREATE TABLE IF NOT EXISTS PRODUCTS
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    BRAND_ID    BIGINT NOT NULL,
    PRICE       DOUBLE PRECISION NOT NULL,
    COLOR VARCHAR(50),
    SIZE VARCHAR(50),
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID),
    FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID),
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP    NULL
);

--changeset kuat:4
CREATE TABLE IF NOT EXISTS ORDERS
(
    ID          BIGSERIAL PRIMARY KEY,
    AUTHOR_ID   BIGINT           NOT NULL,
    PRODUCT_ID  BIGINT           NOT NULL,
    TOTAL_PRICE DOUBLE PRECISION NOT NULL,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP        NULL
);

--changeset kuat:5
CREATE TABLE IF NOT EXISTS ORDER_PRODUCTS
(
    ORDER_ID BIGINT NOT NULL ,
    PRODUCT_ID BIGINT NOT NULL ,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(ID)
)