-- liquibase formatted sql

-- changeset kuat:1
CREATE TABLE roles
(
    ID          BIGSERIAL PRIMARY KEY,
    NAME        VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(255)
);

-- changeset kuat:2
CREATE TABLE users
(
    ID BIGSERIAL PRIMARY KEY ,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL ,
    BIRTHDATE DATE,
    CREATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT  TIMESTAMP        NULL
);

-- changeset kuat:3
CREATE TABLE user_roles
(
    USER_ID BIGINT NOT NULL ,
    ROLE_ID BIGINT NOT NULL ,
    FOREIGN KEY (USER_ID) REFERENCES users(ID) ON DELETE CASCADE ,
    FOREIGN KEY (ROLE_ID) REFERENCES roles(ID) ON DELETE CASCADE
);